"""empty message

Revision ID: 01a0bde86c06
Revises: 8aa02bf12117
Create Date: 2022-09-03 19:31:26.116236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a0bde86c06'
down_revision = '8aa02bf12117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    op.drop_constraint(None, 'job', type_='foreignkey')
    # ### end Alembic commands ###
