"""empty message

Revision ID: 0625652ec957
Revises: 05ec0d90e4d4
Create Date: 2022-08-27 16:50:10.978123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0625652ec957'
down_revision = '05ec0d90e4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('logo', sa.LargeBinary(), nullable=False))
    op.drop_column('job', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('picture', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('job', 'logo')
    # ### end Alembic commands ###
