"""empty message

Revision ID: 34da4b435f42
Revises: 91ec5bb2a1f6
Create Date: 2022-08-28 21:43:42.608442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34da4b435f42'
down_revision = '91ec5bb2a1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
