"""empty message

Revision ID: 434dba144b62
Revises: 704cf14515d9
Create Date: 2022-08-28 17:59:20.555131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434dba144b62'
down_revision = '704cf14515d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('company', sa.String(length=50), nullable=False))
    op.add_column('job', sa.Column('location', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'location')
    op.drop_column('job', 'company')
    # ### end Alembic commands ###
