"""empty message

Revision ID: 65aec1980b8e
Revises: 0625652ec957
Create Date: 2022-08-27 17:02:45.764627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aec1980b8e'
down_revision = '0625652ec957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('filename', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'filename')
    # ### end Alembic commands ###
