"""empty message

Revision ID: 704cf14515d9
Revises: adce480aed00
Create Date: 2022-08-28 17:44:57.430122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '704cf14515d9'
down_revision = 'adce480aed00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('creater_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('job', sa.Column('website', sa.String(length=20), nullable=False))
    op.drop_index('email', table_name='job')
    op.drop_column('job', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('email', 'job', ['email'], unique=False)
    op.drop_column('job', 'website')
    op.drop_table('user')
    # ### end Alembic commands ###
