"""empty message

Revision ID: 8aa02bf12117
Revises: 34da4b435f42
Create Date: 2022-08-29 18:28:30.690956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa02bf12117'
down_revision = '34da4b435f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'user_id')
    # ### end Alembic commands ###
