"""empty message

Revision ID: 91ec5bb2a1f6
Revises: 434dba144b62
Create Date: 2022-08-28 21:43:29.611613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91ec5bb2a1f6'
down_revision = '434dba144b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
