"""empty message

Revision ID: adce480aed00
Revises: 65aec1980b8e
Create Date: 2022-08-27 19:02:18.141293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adce480aed00'
down_revision = '65aec1980b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('logo', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###
